name              "aws-cache"
maintainer        "Shubhajit Saha"
maintainer_email  "suvozit@live.com"
license           "MIT"
description       "Set of recipes to help setup PHP applications ."
version           "1.0.0"
